{{- if and .Values.ingress.enabled .Values.keda.enabled -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "go-web-app.fullname" . }}-scaler
  labels:
    {{- include "go-web-app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    # Dynamically targets the Deployment created by this chart
    name: {{ include "go-web-app.fullname" . }}
  
  # Pulls the configuration from your values.yaml
  minReplicaCount: {{ .Values.keda.minReplicas }}
  maxReplicaCount: {{ .Values.keda.maxReplicas }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc.cluster.local:9090
      metricName: http_requests_per_minute
      threshold: {{ quote .Values.keda.threshold }}
      
#       query: sum(rate(nginx_ingress_controller_requests{ingress="{{ include "go-web-app.fullname" . }}"}[1m])) * 60
        query: sum(rate(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix="ingress_http"}[1m])) * 60
 {{- end }}